project_name: conductor-kit
version: 2

before:
  hooks:
    - go mod tidy

changelog:
  use: github
  sort: asc
  groups:
    - title: Features
      regexp: '^feat'
      order: 0
    - title: Bug Fixes
      regexp: '^fix'
      order: 1
    - title: Documentation
      regexp: '^docs'
      order: 2
    - title: Refactoring
      regexp: '^refactor'
      order: 3
    - title: Testing
      regexp: '^test'
      order: 4
    - title: Others
      order: 999
  filters:
    exclude:
      - '^chore'
      - Merge pull request
      - Merge branch

builds:
  - id: conductor
    main: ./cmd/conductor
    binary: conductor
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.Version={{.Version}}
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - id: conductor
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    files:
      - skills/**
      - commands/**
      - config/**
      - README.md
      - README.ko.md
      - LICENSE

homebrew_casks:
  - name: conductor-kit
    homepage: "https://github.com/Skyline-23/conductor-kit"
    description: "Global skills pack and Go helper for Codex CLI and Claude Code"
    license: "MIT"
    repository:
      owner: Skyline-23
      name: homebrew-conductor-kit
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    ids:
      - conductor
    binaries:
      - conductor
    url:
      verified: "github.com/Skyline-23/conductor-kit"
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
          end
          system_command "#{staged_path}/conductor", args: ["install", "--mode", "link", "--repo", "#{staged_path}", "--force"]
      pre:
        uninstall: |
          if File.exist?("#{staged_path}/conductor")
            system_command "#{staged_path}/conductor", args: ["uninstall", "--force"]
          end
    caveats: |
      Skills/commands were linked into ~/.codex and ~/.claude during install.
      If you need to re-link:
        #{staged_path}/conductor install --mode link --repo #{staged_path} --force
      To fully remove user-level installs:
        conductor uninstall --force
