project_name: conductor-kit
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: conductor
    main: ./cmd/conductor
    binary: conductor
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - id: conductor
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    files:
      - skills/**
      - commands/**
      - config/**
      - README.md
      - README.ko.md
      - LICENSE

brews:
  - name: conductor-kit
    homepage: "https://github.com/Skyline-23/conductor-kit"
    description: "Global skills pack and Go helper for Codex CLI and Claude Code"
    license: "MIT"
    repository:
      owner: Skyline-23
      name: homebrew-conductor-kit
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    directory: Formula
    install: |
      bin.install "conductor"
      (bin/"conductor-background-task").write <<~EOS
        #!/bin/sh
        exec "#{bin}/conductor" background-task "$@"
      EOS
      (bin/"conductor-background-output").write <<~EOS
        #!/bin/sh
        exec "#{bin}/conductor" background-output "$@"
      EOS
      (bin/"conductor-background-cancel").write <<~EOS
        #!/bin/sh
        exec "#{bin}/conductor" background-cancel "$@"
      EOS
      (bin/"conductor-background-batch").write <<~EOS
        #!/bin/sh
        exec "#{bin}/conductor" background-batch "$@"
      EOS
      chmod 0755, [bin/"conductor-background-task", bin/"conductor-background-output", bin/"conductor-background-cancel", bin/"conductor-background-batch"]
      pkgshare.install "skills", "commands", "config"
    post_install: |
      system "#{bin}/conductor", "install", "--mode", "link", "--repo", "#{pkgshare}", "--force"
    caveats: |
      Skills/commands were linked into ~/.codex and ~/.claude during install.
      If you need to re-link:
        conductor install --mode link --repo #{pkgshare} --force
